//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.CustomerServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="CustomerServiceReference.CustomerService")]
    public interface CustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:CustomerService/GetCustomerRegular", ReplyAction="urn:CustomerService/GetCustomerRegularResponse")]
        Entities.Customer GetCustomerRegular(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:CustomerService/GetCustomerRegular", ReplyAction="urn:CustomerService/GetCustomerRegularResponse")]
        System.Threading.Tasks.Task<Entities.Customer> GetCustomerRegularAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:CustomerService/GetCustomerFallible", ReplyAction="urn:CustomerService/GetCustomerFallibleResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entities.Success<Entities.Customer>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entities.BadIdea<Entities.Customer>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entities.Failure<Entities.Customer>))]
        Entities.Fallible<Entities.Customer> GetCustomerFallible(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:CustomerService/GetCustomerFallible", ReplyAction="urn:CustomerService/GetCustomerFallibleResponse")]
        System.Threading.Tasks.Task<Entities.Fallible<Entities.Customer>> GetCustomerFallibleAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerServiceChannel : Client.CustomerServiceReference.CustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<Client.CustomerServiceReference.CustomerService>, Client.CustomerServiceReference.CustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Entities.Customer GetCustomerRegular(int id) {
            return base.Channel.GetCustomerRegular(id);
        }
        
        public System.Threading.Tasks.Task<Entities.Customer> GetCustomerRegularAsync(int id) {
            return base.Channel.GetCustomerRegularAsync(id);
        }
        
        public Entities.Fallible<Entities.Customer> GetCustomerFallible(int id) {
            return base.Channel.GetCustomerFallible(id);
        }
        
        public System.Threading.Tasks.Task<Entities.Fallible<Entities.Customer>> GetCustomerFallibleAsync(int id) {
            return base.Channel.GetCustomerFallibleAsync(id);
        }
    }
}
